version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  www:
    depends_on:
      - db
      - api
    build:
      context: www
    ports:
      - "3000:3000"
  api:
    build:
      context: grafka
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres"
    ports:
      - "9000:9000"
